#ifndef CROSSING_CONSOLES_BLOCK_TYPES_H
#define CROSSING_CONSOLES_BLOCK_TYPES_H

namespace game::world {

enum class BlockType {
  EMPTY_BLOCK,

  WALL_BRICK,
  WALL_ROCK_LIGHT,
  WALL_ROCK_MEDIUM,
  WALL_ROCK_HEAVY,
  WALL_ROCK_FULL,
  WALL_SNOW_LIGHT,
  WALL_SNOW_MEDIUM,
  WALL_SNOW_HEAVY,
  WALL_SNOW_FULL,
  WALL_START = WALL_BRICK,
  WALL_END = WALL_SNOW_FULL,

  PLAYER_UP,
  PLAYER_DOWN,
  PLAYER_LEFT,
  PLAYER_RIGHT,
  PLAYER_DEAD,

  PROJECTILE,

};

}  // namespace game::world

#endif  // CROSSING_CONSOLES_BLOCK_TYPES_H
